[tools]
# Runtime
deno = 'latest'
node = 'latest'
uv = 'latest'

# Package Managers
ni = 'latest'
pnpm = 'latest'

# AI Tools
claude = 'latest'
gemini-cli = 'latest'
codex = 'latest'

# Git Tools
"ubi:d-kuro/gwq" = 'latest'

# Linters/Formatters
hadolint = 'latest'
yamllint = 'latest'
"npm:jsonlint" = 'latest'
"npm:markdownlint-cli" = 'latest'
"npm:oxfmt" = 'latest'
"npm:oxlint" = 'latest'
"npm:stylelint" = 'latest'
"ubi:JohnnyMorganz/StyLua" = 'latest'
"ubi:Kampfkarren/selene" = 'latest'

[tasks.setup]
description = "Install uv tools"
run = """
uv tool install fonttools --with brotli
uv tool install gdtoolkit==4.*
"""
